import { TCurrencyCode, TCurrencyLocalCode } from '../types';
import { CurrencyCode, CurrencyLocale } from '../enums';

export const CurrencyLocaleCode: Record<
  TCurrencyLocalCode,
  TCurrencyCode | TCurrencyCode[]
> = {
  [CurrencyLocale.nl_AW]: [CurrencyCode.ANG, CurrencyCode.AWG],
  [CurrencyLocale.es_BO]: [CurrencyCode.BOB, CurrencyCode.BOV],
  [CurrencyLocale.de_CH]: [CurrencyCode.CHF, CurrencyCode.CHE],
  [CurrencyLocale.es_CL]: [CurrencyCode.CLF, CurrencyCode.CLP],
  [CurrencyLocale.es_CO]: [CurrencyCode.COP, CurrencyCode.COU],
  [CurrencyLocale.es_CU]: [CurrencyCode.CUC, CurrencyCode.CUP],
  [CurrencyLocale.es_MX]: [CurrencyCode.MXN, CurrencyCode.MXV],
  [CurrencyLocale.en_US]: [
    CurrencyCode.USD,
    CurrencyCode.USN,
    CurrencyCode.USS,
  ],
  [CurrencyLocale.es_UY]: [CurrencyCode.UYI, CurrencyCode.UYU],
  [CurrencyLocale.en]: [
    CurrencyCode.XAG,
    CurrencyCode.XAU,
    CurrencyCode.XBA,
    CurrencyCode.XBB,
    CurrencyCode.XBC,
    CurrencyCode.XBD,
    CurrencyCode.XDR,
    CurrencyCode.XFU,
    CurrencyCode.XPD,
    CurrencyCode.XXX,
    CurrencyCode.XPT,
    CurrencyCode.XTS,
  ],
  [CurrencyLocale.en_GB]: CurrencyCode.GBP,
  [CurrencyLocale.ar_AE]: CurrencyCode.AED,
  [CurrencyLocale.ps_AF]: CurrencyCode.AFN,
  [CurrencyLocale.sq_AL]: CurrencyCode.ALL,
  [CurrencyLocale.hy_AM]: CurrencyCode.AMD,
  [CurrencyLocale.pt_AO]: CurrencyCode.AOA,
  [CurrencyLocale.es_AR]: CurrencyCode.ARS,
  [CurrencyLocale.en_AU]: CurrencyCode.AUD,
  [CurrencyLocale.az_AZ]: CurrencyCode.AZN,
  [CurrencyLocale.bs_BA]: CurrencyCode.BAM,
  [CurrencyLocale.en_BB]: CurrencyCode.BBD,
  [CurrencyLocale.bn_BD]: CurrencyCode.BDT,
  [CurrencyLocale.bg_BG]: CurrencyCode.BGN,
  [CurrencyLocale.ar_BH]: CurrencyCode.BHD,
  [CurrencyLocale.fr_BI]: CurrencyCode.BIF,
  [CurrencyLocale.en_BM]: CurrencyCode.BMD,
  [CurrencyLocale.ms_BN]: CurrencyCode.BND,
  [CurrencyLocale.pt_BR]: CurrencyCode.BRL,
  [CurrencyLocale.en_BS]: CurrencyCode.BSD,
  [CurrencyLocale.dz_BT]: CurrencyCode.BTN,
  [CurrencyLocale.en_BW]: CurrencyCode.BWP,
  [CurrencyLocale.be_BY]: CurrencyCode.BYR,
  [CurrencyLocale.en_BZ]: CurrencyCode.BZD,
  [CurrencyLocale.en_CA]: CurrencyCode.CAD,
  [CurrencyLocale.fr_CD]: CurrencyCode.CDF,
  [CurrencyLocale.fr_CH]: CurrencyCode.CHW,
  [CurrencyLocale.zh_CN]: CurrencyCode.CNY,
  [CurrencyLocale.es_CR]: CurrencyCode.CRC,
  [CurrencyLocale.pt_CV]: CurrencyCode.CVE,
  [CurrencyLocale.cs_CZ]: CurrencyCode.CZK,
  [CurrencyLocale.fr_DJ]: CurrencyCode.DJF,
  [CurrencyLocale.da_DK]: CurrencyCode.DKK,
  [CurrencyLocale.es_DO]: CurrencyCode.DOP,
  [CurrencyLocale.ar_DZ]: CurrencyCode.DZD,
  [CurrencyLocale.ar_EG]: CurrencyCode.EGP,
  [CurrencyLocale.ti_ER]: CurrencyCode.ERN,
  [CurrencyLocale.am_ET]: CurrencyCode.ETB,
  [CurrencyLocale.en_FJ]: CurrencyCode.FJD,
  [CurrencyLocale.en_FK]: CurrencyCode.FKP,
  [CurrencyLocale.ka_GE]: CurrencyCode.GEL,
  [CurrencyLocale.en_GH]: CurrencyCode.GHS,
  [CurrencyLocale.en_GI]: CurrencyCode.GIP,
  [CurrencyLocale.en_GM]: CurrencyCode.GMD,
  [CurrencyLocale.fr_GN]: CurrencyCode.GNF,
  [CurrencyLocale.es_GT]: CurrencyCode.GTQ,
  [CurrencyLocale.en_GY]: CurrencyCode.GYD,
  [CurrencyLocale.zh_HK]: CurrencyCode.HKD,
  [CurrencyLocale.es_HN]: CurrencyCode.HNL,
  [CurrencyLocale.hr_HR]: CurrencyCode.HRK,
  [CurrencyLocale.ht_HT]: CurrencyCode.HTG,
  [CurrencyLocale.hu_HU]: CurrencyCode.HUF,
  [CurrencyLocale.id_ID]: CurrencyCode.IDR,
  [CurrencyLocale.he_IL]: CurrencyCode.ILS,
  [CurrencyLocale.hi_IN]: CurrencyCode.INR,
  [CurrencyLocale.ar_IQ]: CurrencyCode.IQD,
  [CurrencyLocale.fa_IR]: CurrencyCode.IRR,
  [CurrencyLocale.is_IS]: CurrencyCode.ISK,
  [CurrencyLocale.en_JM]: CurrencyCode.JMD,
  [CurrencyLocale.ar_JO]: CurrencyCode.JOD,
  [CurrencyLocale.ja_JP]: CurrencyCode.JPY,
  [CurrencyLocale.sw_KE]: CurrencyCode.KES,
  [CurrencyLocale.ky_KG]: CurrencyCode.KGS,
  [CurrencyLocale.km_KH]: CurrencyCode.KHR,
  [CurrencyLocale.ar_KM]: CurrencyCode.KMF,
  [CurrencyLocale.ko_KP]: CurrencyCode.KPW,
  [CurrencyLocale.ko_KR]: CurrencyCode.KRW,
  [CurrencyLocale.ar_KW]: CurrencyCode.KWD,
  [CurrencyLocale.en_KY]: CurrencyCode.KYD,
  [CurrencyLocale.kk_KZ]: CurrencyCode.KZT,
  [CurrencyLocale.lo_LA]: CurrencyCode.LAK,
  [CurrencyLocale.ar_LB]: CurrencyCode.LBP,
  [CurrencyLocale.si_LK]: CurrencyCode.LKR,
  [CurrencyLocale.en_LR]: CurrencyCode.LRD,
  [CurrencyLocale.st_LS]: CurrencyCode.LSL,
  [CurrencyLocale.lt_LT]: CurrencyCode.LTL,
  [CurrencyLocale.lv_LV]: CurrencyCode.LVL,
  [CurrencyLocale.ar_LY]: CurrencyCode.LYD,
  [CurrencyLocale.ar_MA]: CurrencyCode.MAD,
  [CurrencyLocale.ro_MD]: CurrencyCode.MDL,
  [CurrencyLocale.mg_MG]: CurrencyCode.MGA,
  [CurrencyLocale.mk_MK]: CurrencyCode.MKD,
  [CurrencyLocale.my_MM]: CurrencyCode.MMK,
  [CurrencyLocale.mn_MN]: CurrencyCode.MNT,
  [CurrencyLocale.zh_MO]: CurrencyCode.MOP,
  [CurrencyLocale.ar_MR]: CurrencyCode.MRO,
  [CurrencyLocale.en_MU]: CurrencyCode.MUR,
  [CurrencyLocale.dv_MV]: CurrencyCode.MVR,
  [CurrencyLocale.ny_MW]: CurrencyCode.MWK,
  [CurrencyLocale.ms_MY]: CurrencyCode.MYR,
  [CurrencyLocale.pt_MZ]: CurrencyCode.MZN,
  [CurrencyLocale.af_NA]: CurrencyCode.NAD,
  [CurrencyLocale.ig_NG]: CurrencyCode.NGN,
  [CurrencyLocale.es_NI]: CurrencyCode.NIO,
  [CurrencyLocale.nb_NO]: CurrencyCode.NOK,
  [CurrencyLocale.ne_NP]: CurrencyCode.NPR,
  [CurrencyLocale.en_NZ]: CurrencyCode.NZD,
  [CurrencyLocale.ar_OM]: CurrencyCode.OMR,
  [CurrencyLocale.es_PA]: CurrencyCode.PAB,
  [CurrencyLocale.es_PE]: CurrencyCode.PEN,
  [CurrencyLocale.en_PG]: CurrencyCode.PGK,
  [CurrencyLocale.en_PH]: CurrencyCode.PHP,
  [CurrencyLocale.ur_PK]: CurrencyCode.PKR,
  [CurrencyLocale.pl_PL]: CurrencyCode.PLN,
  [CurrencyLocale.es_PY]: CurrencyCode.PYG,
  [CurrencyLocale.ar_QA]: CurrencyCode.QAR,
  [CurrencyLocale.ro_RO]: CurrencyCode.RON,
  [CurrencyLocale.sr_RS]: CurrencyCode.RSD,
  [CurrencyLocale.ru_RU]: CurrencyCode.RUB,
  [CurrencyLocale.rw_RW]: CurrencyCode.RWF,
  [CurrencyLocale.ar_SA]: CurrencyCode.SAR,
  [CurrencyLocale.en_SB]: CurrencyCode.SBD,
  [CurrencyLocale.en_SC]: CurrencyCode.SCR,
  [CurrencyLocale.ar_SD]: CurrencyCode.SDG,
  [CurrencyLocale.sv_SE]: CurrencyCode.SEK,
  [CurrencyLocale.en_SG]: CurrencyCode.SGD,
  [CurrencyLocale.en_SH]: CurrencyCode.SHP,
  [CurrencyLocale.en_SL]: CurrencyCode.SLL,
  [CurrencyLocale.so_SO]: CurrencyCode.SOS,
  [CurrencyLocale.nl_SR]: CurrencyCode.SRD,
  [CurrencyLocale.en_SS]: CurrencyCode.SSP,
  [CurrencyLocale.pt_ST]: CurrencyCode.STD,
  [CurrencyLocale.ar_SY]: CurrencyCode.SYP,
  [CurrencyLocale.ss_SZ]: CurrencyCode.SZL,
  [CurrencyLocale.th_TH]: CurrencyCode.THB,
  [CurrencyLocale.tg_TJ]: CurrencyCode.TJS,
  [CurrencyLocale.tk_TM]: CurrencyCode.TMT,
  [CurrencyLocale.ar_TN]: CurrencyCode.TND,
  [CurrencyLocale.to_TO]: CurrencyCode.TOP,
  [CurrencyLocale.tr_TR]: CurrencyCode.TRY,
  [CurrencyLocale.en_TT]: CurrencyCode.TTD,
  [CurrencyLocale.zh_TW]: CurrencyCode.TWD,
  [CurrencyLocale.sw_TZ]: CurrencyCode.TZS,
  [CurrencyLocale.uk_UA]: CurrencyCode.UAH,
  [CurrencyLocale.sw_UG]: CurrencyCode.UGX,
  [CurrencyLocale.uz_UZ]: CurrencyCode.UZS,
  [CurrencyLocale.es_VE]: CurrencyCode.VEF,
  [CurrencyLocale.vi_VN]: CurrencyCode.VND,
  [CurrencyLocale.en_VU]: CurrencyCode.VUV,
  [CurrencyLocale.sm_WS]: CurrencyCode.WST,
  [CurrencyLocale.fr_CM]: CurrencyCode.XAF,
  [CurrencyLocale.en_VC]: CurrencyCode.XCD,
  [CurrencyLocale.fr_BJ]: CurrencyCode.XOF,
  [CurrencyLocale.fr_PF]: CurrencyCode.XPF,
  [CurrencyLocale.ar_YE]: CurrencyCode.YER,
  [CurrencyLocale.zu_ZA]: CurrencyCode.ZAR,
  [CurrencyLocale.en_ZM]: CurrencyCode.ZMW,
  [CurrencyLocale.nl_BE]: CurrencyCode.EUR,
  [CurrencyLocale.nl_NL]: CurrencyCode.EUR,
  [CurrencyLocale.pt_PT]: CurrencyCode.EUR,
  [CurrencyLocale.es_ES]: CurrencyCode.EUR,
  [CurrencyLocale.fr_BE]: CurrencyCode.EUR,
  [CurrencyLocale.fr_FR]: CurrencyCode.EUR,
  [CurrencyLocale.it_IT]: CurrencyCode.EUR,
  [CurrencyLocale.de_DE]: CurrencyCode.EUR,
  [CurrencyLocale.de_AT]: CurrencyCode.EUR,
  [CurrencyLocale.el_GR]: CurrencyCode.EUR,
  [CurrencyLocale.ee_EE]: CurrencyCode.EUR,
  [CurrencyLocale.fi_FI]: CurrencyCode.EUR,
  [CurrencyLocale.ga_IE]: CurrencyCode.EUR,
  [CurrencyLocale.mt_MT]: CurrencyCode.EUR,
  [CurrencyLocale.sk_SK]: CurrencyCode.EUR,
  [CurrencyLocale.sl_SI]: CurrencyCode.EUR,
  [CurrencyLocale.fr_LU]: CurrencyCode.EUR,
  [CurrencyLocale.de_LU]: CurrencyCode.EUR,
  [CurrencyLocale.lb_LU]: CurrencyCode.EUR,
  [CurrencyLocale.cy_CY]: CurrencyCode.EUR,
  [CurrencyLocale.ad_AD]: CurrencyCode.EUR,
  [CurrencyLocale.al_AL]: CurrencyCode.EUR,
  [CurrencyLocale.by_BY]: CurrencyCode.EUR,
  [CurrencyLocale.ba_BA]: CurrencyCode.EUR,
  [CurrencyLocale.cz_CZ]: CurrencyCode.EUR,
  [CurrencyLocale.dk_DK]: CurrencyCode.EUR,
  [CurrencyLocale.fo_FO]: CurrencyCode.EUR,
  [CurrencyLocale.gi_GI]: CurrencyCode.EUR,
  [CurrencyLocale.il_IL]: CurrencyCode.EUR,
  [CurrencyLocale.xk_XK]: CurrencyCode.EUR,
  [CurrencyLocale.li_LI]: CurrencyCode.EUR,
  [CurrencyLocale.lu_LU]: CurrencyCode.EUR,
  [CurrencyLocale.md_MD]: CurrencyCode.EUR,
  [CurrencyLocale.mc_MC]: CurrencyCode.EUR,
  [CurrencyLocale.me_ME]: CurrencyCode.EUR,
  [CurrencyLocale.no_NO]: CurrencyCode.EUR,
  [CurrencyLocale.rs_RS]: CurrencyCode.EUR,
  [CurrencyLocale.sm_SM]: CurrencyCode.EUR,
  [CurrencyLocale.si_SI]: CurrencyCode.EUR,
  [CurrencyLocale.se_SE]: CurrencyCode.EUR,
  [CurrencyLocale.ch_CH]: CurrencyCode.EUR,
  [CurrencyLocale.ua_UA]: CurrencyCode.EUR,
  [CurrencyLocale.va_VA]: CurrencyCode.EUR,
};

export const CurrencyCodeLocale: Record<
  TCurrencyCode,
  TCurrencyLocalCode | TCurrencyLocalCode[]
> = {
  AED: CurrencyLocale.ar_AE,
  AFN: CurrencyLocale.ps_AF,
  ALL: CurrencyLocale.sq_AL,
  AMD: CurrencyLocale.hy_AM,
  ANG: CurrencyLocale.nl_AW,
  AOA: CurrencyLocale.pt_AO,
  ARS: CurrencyLocale.es_AR,
  AUD: CurrencyLocale.en_AU,
  AWG: CurrencyLocale.nl_AW,
  AZN: CurrencyLocale.az_AZ,
  BAM: CurrencyLocale.bs_BA,
  BBD: CurrencyLocale.en_BB,
  BDT: CurrencyLocale.bn_BD,
  BGN: CurrencyLocale.bg_BG,
  BHD: CurrencyLocale.ar_BH,
  BIF: CurrencyLocale.fr_BI,
  BMD: CurrencyLocale.en_BM,
  BND: CurrencyLocale.ms_BN,
  BOB: CurrencyLocale.es_BO,
  BOV: CurrencyLocale.es_BO,
  BRL: CurrencyLocale.pt_BR,
  BSD: CurrencyLocale.en_BS,
  BTN: CurrencyLocale.dz_BT,
  BWP: CurrencyLocale.en_BW,
  BYR: CurrencyLocale.be_BY,
  BZD: CurrencyLocale.en_BZ,
  CAD: CurrencyLocale.en_CA,
  CDF: CurrencyLocale.fr_CD,
  CHE: CurrencyLocale.de_CH,
  CHF: CurrencyLocale.de_CH,
  CHW: CurrencyLocale.fr_CH,
  CLF: CurrencyLocale.es_CL,
  CLP: CurrencyLocale.es_CL,
  CNY: CurrencyLocale.zh_CN,
  COP: CurrencyLocale.es_CO,
  COU: CurrencyLocale.es_CO,
  CRC: CurrencyLocale.es_CR,
  CUC: CurrencyLocale.es_CU,
  CUP: CurrencyLocale.es_CU,
  CVE: CurrencyLocale.pt_CV,
  CZK: CurrencyLocale.cs_CZ,
  DJF: CurrencyLocale.fr_DJ,
  DKK: CurrencyLocale.da_DK,
  DOP: CurrencyLocale.es_DO,
  DZD: CurrencyLocale.ar_DZ,
  EGP: CurrencyLocale.ar_EG,
  ERN: CurrencyLocale.ti_ER,
  ETB: CurrencyLocale.am_ET,
  EUR: [
    CurrencyLocale.de_AT,
    CurrencyLocale.fr_BE,
    CurrencyLocale.nl_BE,
    CurrencyLocale.de_DE,
    CurrencyLocale.el_GR,
    CurrencyLocale.es_ES,
    CurrencyLocale.ee_EE,
    CurrencyLocale.fi_FI,
    CurrencyLocale.fr_FR,
    CurrencyLocale.ga_IE,
    CurrencyLocale.it_IT,
    CurrencyLocale.lv_LV,
    CurrencyLocale.lt_LT,
    CurrencyLocale.mt_MT,
    CurrencyLocale.nl_NL,
    CurrencyLocale.pt_PT,
    CurrencyLocale.sk_SK,
    CurrencyLocale.sl_SI,
    CurrencyLocale.fr_LU,
    CurrencyLocale.de_LU,
    CurrencyLocale.lb_LU,
    CurrencyLocale.cy_CY,
    CurrencyLocale.ad_AD,
    CurrencyLocale.al_AL,
    CurrencyLocale.by_BY,
    CurrencyLocale.ba_BA,
    CurrencyLocale.bg_BG,
    CurrencyLocale.hr_HR,
    CurrencyLocale.cz_CZ,
    CurrencyLocale.dk_DK,
    CurrencyLocale.fo_FO,
    CurrencyLocale.gi_GI,
    CurrencyLocale.hu_HU,
    CurrencyLocale.is_IS,
    CurrencyLocale.il_IL,
    CurrencyLocale.xk_XK,
    CurrencyLocale.li_LI,
    CurrencyLocale.lu_LU,
    CurrencyLocale.mk_MK,
    CurrencyLocale.md_MD,
    CurrencyLocale.mc_MC,
    CurrencyLocale.me_ME,
    CurrencyLocale.no_NO,
    CurrencyLocale.pl_PL,
    CurrencyLocale.ro_RO,
    CurrencyLocale.rs_RS,
    CurrencyLocale.sm_SM,
    CurrencyLocale.sk_SK,
    CurrencyLocale.si_SI,
    CurrencyLocale.se_SE,
    CurrencyLocale.ch_CH,
    CurrencyLocale.tr_TR,
    CurrencyLocale.ua_UA,
    CurrencyLocale.va_VA,
  ],
  FJD: CurrencyLocale.en_FJ,
  FKP: CurrencyLocale.en_FK,
  GBP: CurrencyLocale.en_GB,
  GEL: CurrencyLocale.ka_GE,
  GHS: CurrencyLocale.en_GH,
  GIP: CurrencyLocale.en_GI,
  GMD: CurrencyLocale.en_GM,
  GNF: CurrencyLocale.fr_GN,
  GTQ: CurrencyLocale.es_GT,
  GYD: CurrencyLocale.en_GY,
  HKD: CurrencyLocale.zh_HK,
  HNL: CurrencyLocale.es_HN,
  HRK: CurrencyLocale.hr_HR,
  HTG: CurrencyLocale.ht_HT,
  HUF: CurrencyLocale.hu_HU,
  IDR: CurrencyLocale.id_ID,
  ILS: CurrencyLocale.he_IL,
  INR: CurrencyLocale.hi_IN,
  IQD: CurrencyLocale.ar_IQ,
  IRR: CurrencyLocale.fa_IR,
  ISK: CurrencyLocale.is_IS,
  JMD: CurrencyLocale.en_JM,
  JOD: CurrencyLocale.ar_JO,
  JPY: CurrencyLocale.ja_JP,
  KES: CurrencyLocale.sw_KE,
  KGS: CurrencyLocale.ky_KG,
  KHR: CurrencyLocale.km_KH,
  KMF: CurrencyLocale.ar_KM,
  KPW: CurrencyLocale.ko_KP,
  KRW: CurrencyLocale.ko_KR,
  KWD: CurrencyLocale.ar_KW,
  KYD: CurrencyLocale.en_KY,
  KZT: CurrencyLocale.kk_KZ,
  LAK: CurrencyLocale.lo_LA,
  LBP: CurrencyLocale.ar_LB,
  LKR: CurrencyLocale.si_LK,
  LRD: CurrencyLocale.en_LR,
  LSL: CurrencyLocale.st_LS,
  LTL: CurrencyLocale.lt_LT,
  LVL: CurrencyLocale.lv_LV,
  LYD: CurrencyLocale.ar_LY,
  MAD: CurrencyLocale.ar_MA,
  MDL: CurrencyLocale.ro_MD,
  MGA: CurrencyLocale.mg_MG,
  MKD: CurrencyLocale.mk_MK,
  MMK: CurrencyLocale.my_MM,
  MNT: CurrencyLocale.mn_MN,
  MOP: CurrencyLocale.zh_MO,
  MRO: CurrencyLocale.ar_MR,
  MUR: CurrencyLocale.en_MU,
  MVR: CurrencyLocale.dv_MV,
  MWK: CurrencyLocale.ny_MW,
  MXN: CurrencyLocale.es_MX,
  MXV: CurrencyLocale.es_MX,
  MYR: CurrencyLocale.ms_MY,
  MZN: CurrencyLocale.pt_MZ,
  NAD: CurrencyLocale.af_NA,
  NGN: CurrencyLocale.ig_NG,
  NIO: CurrencyLocale.es_NI,
  NOK: CurrencyLocale.nb_NO,
  NPR: CurrencyLocale.ne_NP,
  NZD: CurrencyLocale.en_NZ,
  OMR: CurrencyLocale.ar_OM,
  PAB: CurrencyLocale.es_PA,
  PEN: CurrencyLocale.es_PE,
  PGK: CurrencyLocale.en_PG,
  PHP: CurrencyLocale.en_PH,
  PKR: CurrencyLocale.ur_PK,
  PLN: CurrencyLocale.pl_PL,
  PYG: CurrencyLocale.es_PY,
  QAR: CurrencyLocale.ar_QA,
  RON: CurrencyLocale.ro_RO,
  RSD: CurrencyLocale.sr_RS,
  RUB: CurrencyLocale.ru_RU,
  RWF: CurrencyLocale.rw_RW,
  SAR: CurrencyLocale.ar_SA,
  SBD: CurrencyLocale.en_SB,
  SCR: CurrencyLocale.en_SC,
  SDG: CurrencyLocale.ar_SD,
  SEK: CurrencyLocale.sv_SE,
  SGD: CurrencyLocale.en_SG,
  SHP: CurrencyLocale.en_SH,
  SLL: CurrencyLocale.en_SL,
  SOS: CurrencyLocale.so_SO,
  SRD: CurrencyLocale.nl_SR,
  SSP: CurrencyLocale.en_SS,
  STD: CurrencyLocale.pt_ST,
  SYP: CurrencyLocale.ar_SY,
  SZL: CurrencyLocale.ss_SZ,
  THB: CurrencyLocale.th_TH,
  TJS: CurrencyLocale.tg_TJ,
  TMT: CurrencyLocale.tk_TM,
  TND: CurrencyLocale.ar_TN,
  TOP: CurrencyLocale.to_TO,
  TRY: CurrencyLocale.tr_TR,
  TTD: CurrencyLocale.en_TT,
  TWD: CurrencyLocale.zh_TW,
  TZS: CurrencyLocale.sw_TZ,
  UAH: CurrencyLocale.uk_UA,
  UGX: CurrencyLocale.sw_UG,
  USD: CurrencyLocale.en_US,
  USN: CurrencyLocale.en_US,
  USS: CurrencyLocale.en_US,
  UYI: CurrencyLocale.es_UY,
  UYU: CurrencyLocale.es_UY,
  UZS: CurrencyLocale.uz_UZ,
  VEF: CurrencyLocale.es_VE,
  VND: CurrencyLocale.vi_VN,
  VUV: CurrencyLocale.en_VU,
  WST: CurrencyLocale.sm_WS,
  XAF: CurrencyLocale.fr_CM,
  XAG: CurrencyLocale.en,
  XAU: CurrencyLocale.en,
  XBA: CurrencyLocale.en,
  XBB: CurrencyLocale.en,
  XBC: CurrencyLocale.en,
  XBD: CurrencyLocale.en,
  XCD: CurrencyLocale.en_VC,
  XDR: CurrencyLocale.en,
  XFU: CurrencyLocale.en,
  XOF: CurrencyLocale.fr_BJ,
  XPD: CurrencyLocale.en,
  XPF: CurrencyLocale.fr_PF,
  XPT: CurrencyLocale.en,
  XTS: CurrencyLocale.en,
  XXX: CurrencyLocale.en,
  YER: CurrencyLocale.ar_YE,
  ZAR: CurrencyLocale.zu_ZA,
  ZMW: CurrencyLocale.en_ZM,
};
