import { TCurrencyCode, TCurrencyLocalCode } from '../types';
import { CurrencyCode, CurrencyLocale } from '../enums';

export const CurrencyLocaleCode: Record<
  TCurrencyLocalCode,
  TCurrencyCode | TCurrencyCode[]
> = {
  [CurrencyLocale.nl_AW]: [CurrencyCode.ANG, CurrencyCode.AWG],
  [CurrencyLocale.es_BO]: [CurrencyCode.BOB, CurrencyCode.BOV],
  [CurrencyLocale.de_CH]: [CurrencyCode.CHF, CurrencyCode.CHE],
  [CurrencyLocale.es_CL]: [CurrencyCode.CLF, CurrencyCode.CLP],
  [CurrencyLocale.es_CO]: [CurrencyCode.COP, CurrencyCode.COU],
  [CurrencyLocale.es_CU]: [CurrencyCode.CUC, CurrencyCode.CUP],
  [CurrencyLocale.en_GB]: [CurrencyCode.EUR, CurrencyCode.GBP],
  [CurrencyLocale.es_MX]: [CurrencyCode.MXN, CurrencyCode.MXV],
  [CurrencyLocale.en_US]: [
    CurrencyCode.USD,
    CurrencyCode.USN,
    CurrencyCode.USS,
  ],
  [CurrencyLocale.es_UY]: [CurrencyCode.UYI, CurrencyCode.UYU],
  [CurrencyLocale.en]: [
    CurrencyCode.XAG,
    CurrencyCode.XAU,
    CurrencyCode.XBA,
    CurrencyCode.XBB,
    CurrencyCode.XBC,
    CurrencyCode.XBD,
    CurrencyCode.XDR,
    CurrencyCode.XFU,
    CurrencyCode.XPD,
    CurrencyCode.XXX,
    CurrencyCode.XPT,
    CurrencyCode.XTS,
  ],
  [CurrencyLocale.ar_AE]: CurrencyCode.AED,
  [CurrencyLocale.ps_AF]: CurrencyCode.AFN,
  [CurrencyLocale.sq_AL]: CurrencyCode.ALL,
  [CurrencyLocale.hy_AM]: CurrencyCode.AMD,
  [CurrencyLocale.pt_AO]: CurrencyCode.AOA,
  [CurrencyLocale.es_AR]: CurrencyCode.ARS,
  [CurrencyLocale.en_AU]: CurrencyCode.AUD,
  [CurrencyLocale.az_AZ]: CurrencyCode.AZN,
  [CurrencyLocale.bs_BA]: CurrencyCode.BAM,
  [CurrencyLocale.en_BB]: CurrencyCode.BBD,
  [CurrencyLocale.bn_BD]: CurrencyCode.BDT,
  [CurrencyLocale.bg_BG]: CurrencyCode.BGN,
  [CurrencyLocale.ar_BH]: CurrencyCode.BHD,
  [CurrencyLocale.fr_BI]: CurrencyCode.BIF,
  [CurrencyLocale.en_BM]: CurrencyCode.BMD,
  [CurrencyLocale.ms_BN]: CurrencyCode.BND,
  [CurrencyLocale.pt_BR]: CurrencyCode.BRL,
  [CurrencyLocale.en_BS]: CurrencyCode.BSD,
  [CurrencyLocale.dz_BT]: CurrencyCode.BTN,
  [CurrencyLocale.en_BW]: CurrencyCode.BWP,
  [CurrencyLocale.be_BY]: CurrencyCode.BYR,
  [CurrencyLocale.en_BZ]: CurrencyCode.BZD,
  [CurrencyLocale.en_CA]: CurrencyCode.CAD,
  [CurrencyLocale.fr_CD]: CurrencyCode.CDF,
  [CurrencyLocale.fr_CH]: CurrencyCode.CHW,
  [CurrencyLocale.zh_CN]: CurrencyCode.CNY,
  [CurrencyLocale.es_CR]: CurrencyCode.CRC,
  [CurrencyLocale.pt_CV]: CurrencyCode.CVE,
  [CurrencyLocale.cs_CZ]: CurrencyCode.CZK,
  [CurrencyLocale.fr_DJ]: CurrencyCode.DJF,
  [CurrencyLocale.da_DK]: CurrencyCode.DKK,
  [CurrencyLocale.es_DO]: CurrencyCode.DOP,
  [CurrencyLocale.ar_DZ]: CurrencyCode.DZD,
  [CurrencyLocale.ar_EG]: CurrencyCode.EGP,
  [CurrencyLocale.ti_ER]: CurrencyCode.ERN,
  [CurrencyLocale.am_ET]: CurrencyCode.ETB,
  [CurrencyLocale.en_FJ]: CurrencyCode.FJD,
  [CurrencyLocale.en_FK]: CurrencyCode.FKP,
  [CurrencyLocale.ka_GE]: CurrencyCode.GEL,
  [CurrencyLocale.en_GH]: CurrencyCode.GHS,
  [CurrencyLocale.en_GI]: CurrencyCode.GIP,
  [CurrencyLocale.en_GM]: CurrencyCode.GMD,
  [CurrencyLocale.fr_GN]: CurrencyCode.GNF,
  [CurrencyLocale.es_GT]: CurrencyCode.GTQ,
  [CurrencyLocale.en_GY]: CurrencyCode.GYD,
  [CurrencyLocale.zh_HK]: CurrencyCode.HKD,
  [CurrencyLocale.es_HN]: CurrencyCode.HNL,
  [CurrencyLocale.hr_HR]: CurrencyCode.HRK,
  [CurrencyLocale.ht_HT]: CurrencyCode.HTG,
  [CurrencyLocale.hu_HU]: CurrencyCode.HUF,
  [CurrencyLocale.id_ID]: CurrencyCode.IDR,
  [CurrencyLocale.he_IL]: CurrencyCode.ILS,
  [CurrencyLocale.hi_IN]: CurrencyCode.INR,
  [CurrencyLocale.ar_IQ]: CurrencyCode.IQD,
  [CurrencyLocale.fa_IR]: CurrencyCode.IRR,
  [CurrencyLocale.is_IS]: CurrencyCode.ISK,
  [CurrencyLocale.en_JM]: CurrencyCode.JMD,
  [CurrencyLocale.ar_JO]: CurrencyCode.JOD,
  [CurrencyLocale.ja_JP]: CurrencyCode.JPY,
  [CurrencyLocale.sw_KE]: CurrencyCode.KES,
  [CurrencyLocale.ky_KG]: CurrencyCode.KGS,
  [CurrencyLocale.km_KH]: CurrencyCode.KHR,
  [CurrencyLocale.ar_KM]: CurrencyCode.KMF,
  [CurrencyLocale.ko_KP]: CurrencyCode.KPW,
  [CurrencyLocale.ko_KR]: CurrencyCode.KRW,
  [CurrencyLocale.ar_KW]: CurrencyCode.KWD,
  [CurrencyLocale.en_KY]: CurrencyCode.KYD,
  [CurrencyLocale.kk_KZ]: CurrencyCode.KZT,
  [CurrencyLocale.lo_LA]: CurrencyCode.LAK,
  [CurrencyLocale.ar_LB]: CurrencyCode.LBP,
  [CurrencyLocale.si_LK]: CurrencyCode.LKR,
  [CurrencyLocale.en_LR]: CurrencyCode.LRD,
  [CurrencyLocale.st_LS]: CurrencyCode.LSL,
  [CurrencyLocale.lt_LT]: CurrencyCode.LTL,
  [CurrencyLocale.lv_LV]: CurrencyCode.LVL,
  [CurrencyLocale.ar_LY]: CurrencyCode.LYD,
  [CurrencyLocale.ar_MA]: CurrencyCode.MAD,
  [CurrencyLocale.ro_MD]: CurrencyCode.MDL,
  [CurrencyLocale.mg_MG]: CurrencyCode.MGA,
  [CurrencyLocale.mk_MK]: CurrencyCode.MKD,
  [CurrencyLocale.my_MM]: CurrencyCode.MMK,
  [CurrencyLocale.mn_MN]: CurrencyCode.MNT,
  [CurrencyLocale.zh_MO]: CurrencyCode.MOP,
  [CurrencyLocale.ar_MR]: CurrencyCode.MRO,
  [CurrencyLocale.en_MU]: CurrencyCode.MUR,
  [CurrencyLocale.dv_MV]: CurrencyCode.MVR,
  [CurrencyLocale.ny_MW]: CurrencyCode.MWK,
  [CurrencyLocale.ms_MY]: CurrencyCode.MYR,
  [CurrencyLocale.pt_MZ]: CurrencyCode.MZN,
  [CurrencyLocale.af_NA]: CurrencyCode.NAD,
  [CurrencyLocale.ig_NG]: CurrencyCode.NGN,
  [CurrencyLocale.es_NI]: CurrencyCode.NIO,
  [CurrencyLocale.nb_NO]: CurrencyCode.NOK,
  [CurrencyLocale.ne_NP]: CurrencyCode.NPR,
  [CurrencyLocale.en_NZ]: CurrencyCode.NZD,
  [CurrencyLocale.ar_OM]: CurrencyCode.OMR,
  [CurrencyLocale.es_PA]: CurrencyCode.PAB,
  [CurrencyLocale.es_PE]: CurrencyCode.PEN,
  [CurrencyLocale.en_PG]: CurrencyCode.PGK,
  [CurrencyLocale.en_PH]: CurrencyCode.PHP,
  [CurrencyLocale.ur_PK]: CurrencyCode.PKR,
  [CurrencyLocale.pl_PL]: CurrencyCode.PLN,
  [CurrencyLocale.es_PY]: CurrencyCode.PYG,
  [CurrencyLocale.ar_QA]: CurrencyCode.QAR,
  [CurrencyLocale.ro_RO]: CurrencyCode.RON,
  [CurrencyLocale.sr_RS]: CurrencyCode.RSD,
  [CurrencyLocale.ru_RU]: CurrencyCode.RUB,
  [CurrencyLocale.rw_RW]: CurrencyCode.RWF,
  [CurrencyLocale.ar_SA]: CurrencyCode.SAR,
  [CurrencyLocale.en_SB]: CurrencyCode.SBD,
  [CurrencyLocale.en_SC]: CurrencyCode.SCR,
  [CurrencyLocale.ar_SD]: CurrencyCode.SDG,
  [CurrencyLocale.sv_SE]: CurrencyCode.SEK,
  [CurrencyLocale.en_SG]: CurrencyCode.SGD,
  [CurrencyLocale.en_SH]: CurrencyCode.SHP,
  [CurrencyLocale.en_SL]: CurrencyCode.SLL,
  [CurrencyLocale.so_SO]: CurrencyCode.SOS,
  [CurrencyLocale.nl_SR]: CurrencyCode.SRD,
  [CurrencyLocale.en_SS]: CurrencyCode.SSP,
  [CurrencyLocale.pt_ST]: CurrencyCode.STD,
  [CurrencyLocale.ar_SY]: CurrencyCode.SYP,
  [CurrencyLocale.ss_SZ]: CurrencyCode.SZL,
  [CurrencyLocale.th_TH]: CurrencyCode.THB,
  [CurrencyLocale.tg_TJ]: CurrencyCode.TJS,
  [CurrencyLocale.tk_TM]: CurrencyCode.TMT,
  [CurrencyLocale.ar_TN]: CurrencyCode.TND,
  [CurrencyLocale.to_TO]: CurrencyCode.TOP,
  [CurrencyLocale.tr_TR]: CurrencyCode.TRY,
  [CurrencyLocale.en_TT]: CurrencyCode.TTD,
  [CurrencyLocale.zh_TW]: CurrencyCode.TWD,
  [CurrencyLocale.sw_TZ]: CurrencyCode.TZS,
  [CurrencyLocale.uk_UA]: CurrencyCode.UAH,
  [CurrencyLocale.sw_UG]: CurrencyCode.UGX,
  [CurrencyLocale.uz_UZ]: CurrencyCode.UZS,
  [CurrencyLocale.es_VE]: CurrencyCode.VEF,
  [CurrencyLocale.vi_VN]: CurrencyCode.VND,
  [CurrencyLocale.en_VU]: CurrencyCode.VUV,
  [CurrencyLocale.sm_WS]: CurrencyCode.WST,
  [CurrencyLocale.fr_CM]: CurrencyCode.XAF,
  [CurrencyLocale.en_VC]: CurrencyCode.XCD,
  [CurrencyLocale.fr_BJ]: CurrencyCode.XOF,
  [CurrencyLocale.fr_PF]: CurrencyCode.XPF,
  [CurrencyLocale.ar_YE]: CurrencyCode.YER,
  [CurrencyLocale.zu_ZA]: CurrencyCode.ZAR,
  [CurrencyLocale.en_ZM]: CurrencyCode.ZMW,
};
