name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      packages: 'write'
      actions: 'read'
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Validate commits
        run: |
          npm install -g @commitlint/{config-conventional,cli}
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
          commitlint --from=master --to=HEAD
      - name: Update package.json
        run: |
          if [[ $(git log -1 | grep -o fix:) ]]; 
            then npm version patch -m "Upgrade to patch %s" --no-git-tag-version
          elif [[ $(git log -1 | grep -o feat:) ]]; 
            then npm version minor -m "Upgrade to minor %s" --no-git-tag-version
          elif [[ $(git log -1 | grep -o release:) ]]; 
            then npm version major -m "Upgrade to major %s" --no-git-tag-version
          else
            echo "Commit message does not match any versioning convention. Skipping version increment."
          fi

          git push origin master --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies 🔧
        run: npm ci && npm i rimraf
      - name: Build version
        run: npm run build
      - name: Build docs
        run: npm run build:docs && npm install -g ts-node
      - uses: actions/checkout@v2
      - name: Publish docs to github pages
        run:  |
          echo 'Deploying docs!'
          cd docs
          touch .nojekyll
          git init
          git add .
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "docs(docs): update gh-pages"
          git fetch --prune --unshallow
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/gaignoux/currency" master:gh-pages
          echo 'Docs deployed!'
      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
